"""Recommendations router.

Endpoints:
  GET /api/recommendations/{incident_id}  — root cause + ranked remediation actions
"""
from __future__ import annotations

import structlog
from fastapi import APIRouter, HTTPException, status

from app.models.recommendations import RecommendationResponse
from app.services import recommendation_service

log = structlog.get_logger(__name__)

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


@router.get(
    "/{incident_id}",
    response_model=RecommendationResponse,
    summary="Get recommendations for an incident",
    description=(
        "Returns the confirmed root cause analysis and prioritised remediation actions "
        "generated by the Commander agent for the given incident."
    ),
    responses={404: {"description": "Incident not found or analysis not yet complete"}},
)
async def get_recommendations(incident_id: str) -> RecommendationResponse:
    recommendations = await recommendation_service.get_recommendations(incident_id)
    if recommendations is None:
        log.warning("recommendations.not_found", incident_id=incident_id)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No recommendations available for incident '{incident_id}'.",
        )
    log.info(
        "recommendations.fetched",
        incident_id=incident_id,
        action_count=len(recommendations.actions),
    )
    return recommendations
